import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { getAnalyticsData, getDpcSession } from "../../firebase/firestoreService";
import { useI18n } from "../../i18n/I18nContext";

export default function AnalyticsDashboard() {
  const { t } = useI18n(); const navigate = useNavigate(); const [session] = useState(getDpcSession); const data = getAnalyticsData();
  if (!session) { navigate("/dpc", { replace:true }); return null; }
  const max = Math.max(...data.bookingsByHour.map((entry) => entry.count));
  return <main style={{ maxWidth:560, margin:"0 auto" }}><header style={{ background:"#245A78", color:"white", padding:"var(--sp-5)", display:"flex", alignItems:"center", gap:12 }}><button onClick={() => navigate("/dpc/dashboard")} style={{ color:"inherit", fontSize:22 }}>←</button><h1 style={{ color:"inherit" }}>📊 {t("analytics_title")}</h1></header><section style={{ padding:"var(--sp-4)", display:"grid", gap:"var(--sp-4)" }}><article style={{ background:"var(--paper)", padding:"var(--sp-4)", borderRadius:"var(--r-md)", boxShadow:"var(--sh-sm)" }}><h2 style={{ fontSize:"var(--fs-lg)" }}>{t("analytics_load")}</h2><div style={{ display:"grid", gap:8, marginTop:12 }}>{data.bookingsByHour.map((entry) => <div key={entry.hour} style={{ display:"grid", gridTemplateColumns:"48px 1fr 28px", gap:8, alignItems:"center" }}><small>{entry.hour}</small><div style={{ height:12, background:"var(--tarpaulin-100)", borderRadius:99 }}><div style={{ width:`${entry.count / max * 100}%`, height:"100%", background:"var(--paddy-gold-500)", borderRadius:99 }} /></div><strong>{entry.count}</strong></div>)}</div></article><article style={{ background:"var(--paper)", padding:"var(--sp-4)", borderRadius:"var(--r-md)", boxShadow:"var(--sh-sm)" }}><h2 style={{ fontSize:"var(--fs-lg)" }}>{t("analytics_channels")}</h2><p>App {data.channelMix.app} · WhatsApp {data.channelMix.whatsapp} · IVR {data.channelMix.ivr} · Voice {data.channelMix.voice_assistant}</p></article><article style={{ background:"var(--paper)", padding:"var(--sp-4)", borderRadius:"var(--r-md)", boxShadow:"var(--sh-sm)" }}><h2 style={{ fontSize:"var(--fs-lg)" }}>{t("analytics_pendency")}</h2>{data.pendingPayments.map((payment) => <div key={payment.bookingId} style={{ padding:"var(--sp-2) 0", borderBottom:"1px solid var(--tarpaulin-100)" }}><strong>{payment.farmerName}</strong> — ₹{payment.amount.toLocaleString("en-IN")} <span style={{ color:"var(--danger-500)" }}>({payment.daysStuck} {t("days_stuck")})</span></div>)}</article></section></main>;
}
